dam/applications/alimentos/urls.py
from django.urls import path
from .views import (
                    BuscarAlimentos,
                    ListaAlimentos,
                    AgregarAlimento,
                    BorrarAlimento,
                    EditarAlimento,
                    BuscarAlimentoListApiView,
                    AlimentoConsumidoListApiView,)

app_name="alimentos_urls"

urlpatterns = [
    path('listar-alimentos/<int:pk>/',BuscarAlimentos.as_view(),name="listar-alimentos"),
    path('lista-alimentos/',ListaAlimentos.as_view(),name="listaalimentos"),
    path('agregar-alimento/',AgregarAlimento.as_view(),name="agregaralimento"),
    path('eliminar-alimento/<int:pk>/',BorrarAlimento.as_view(),name="eliminaralimento"),
    path('editar-alimento/<int:pk>/',EditarAlimento.as_view(),name="editaralimento"),
    #apis
    path('api/alimentos/buscar/',BuscarAlimentoListApiView.as_view(),name="buscaralimentoapi"),
    path('api/alimentos-consumidos/buscar/',AlimentoConsumidoListApiView.as_view(),name="buscaralimentoconsumidoapi"),


]

dam/dam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from applications.users.views import Index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/',include('applications.users.urls')),
    path('mascotas/',include('applications.mascotas.urls')),
    path('alimentos/',include('applications.alimentos.urls')),
    path('diario/',include('applications.diario.urls',namespace='diaro_urls')),
    path('',Index.as_view(),name="index")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dam/applications/alimentos/models.py
from django.db import models
from django.db.models.signals import post_delete,post_save,pre_save

from applications.users.models import User
from applications.diario.models import Diario
from .managers import AlimentoManager,AlimentoConsumidoManager

TIPO_MASCOTA_CHOICES=(
    ('Gato','Gato'),
    ('Perro','Perro'),
)


class Alimento(models.Model):
    nombre=models.CharField(max_length=50,blank=False)
    marca=models.CharField(max_length=50,blank=False)
    descripcion=models.CharField(max_length=70,blank=False)
    #numeros hasta 999 con 2 posiciones decimales
    calorias=models.PositiveIntegerField(blank=False,help_text="por kg")
    creada_por=models.ForeignKey(User,on_delete=models.CASCADE)
    creada_el=models.DateField(auto_now_add=True)
    tipo_mascota=models.CharField(max_length=5,choices=TIPO_MASCOTA_CHOICES,default='Gato',blank=False)


    objects=AlimentoManager()


    def __str__(self):
        return str(self.id)+' '+self.nombre

 
class AlimentoConsumido(models.Model):
    alimento=models.ForeignKey(Alimento,on_delete=models.CASCADE)
    diario=models.ForeignKey(Diario,on_delete=models.CASCADE)
    cantidad=models.PositiveIntegerField()
    total_cal=models.PositiveIntegerField()

    objects=AlimentoConsumidoManager()

    def __str__(self):
        return str(self.id)+' '+self.alimento.nombre

    
    
def update_total_cal_borrar(sender,instance,**kwargs):
    #actualizamos total calorias al borrar alimento
    print('update total calorias despues de borrar alimento')
    instance.diario.total_cal-=instance.total_cal
    instance.diario.save()


def update_calorias_alimento_consumido(sender,instance,**kwargs):
    #actualizamos las calorias del alimento al ser actualizado

    calorias_gramo=(int((instance.alimento.calorias)/1000))
    nuevo_total_cal=(
        ((int(instance.cantidad))*calorias_gramo)

        )
    AlimentoConsumido.objects.filter(pk=instance.pk).update(total_cal=nuevo_total_cal)

    alimentos=AlimentoConsumido.objects.buscar_alimentos_consumidos(instance.diario)
    caloriastotal=0
    for i in alimentos:
        print('alimento: {}'.format(i))
        caloriastotal+=i.total_cal
    
    instance.diario.total_cal=caloriastotal
    instance.diario.save()

    print('update calorias totales')



post_delete.connect(update_total_cal_borrar,sender=AlimentoConsumido)
post_save.connect(update_calorias_alimento_consumido,sender=AlimentoConsumido)



        

    



    

dam/applications/alimentos/forms.py
from django import forms
from .models import AlimentoConsumido,Alimento

class BusquedaForm(forms.Form):
    
    busqueda = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'Ingrese busqueda aqui',
                'class': 'input-group-field',
            }
        )
    )

class EditarAlimentoForm(forms.ModelForm):
    class Meta:
        #modelo al que se conecta
        model=Alimento
        fields=(
            'nombre',
            'marca',
            'descripcion',
            'calorias',    
        )

    def __init__(self, *args, **kwargs):
        #saco el id de los kwargs
        alimentoid=kwargs.pop('pk','')
        #llamamos al constructor de la clase padre
        super(EditarAlimentoForm, self).__init__(*args, **kwargs)
        #y podemos acceder a las propiedades de los campos
      
        alimento=Alimento.objects.get(pk=alimentoid)
        self.fields['nombre'].initial=alimento.nombre
        self.fields['marca'].initial=alimento.marca
        self.fields['descripcion'].initial=alimento.descripcion
        self.fields['calorias'].initial=alimento.calorias


class DiarioForm(forms.ModelForm):
    class Meta:
        #modelo al que se conecta
        model=AlimentoConsumido
        fields=('id',)

dam/applications/alimentos/views.py
from rest_framework.generics import ListAPIView

from django.contrib import messages
from django.views.generic.base import TemplateView
from django.views.generic.edit import (CreateView, 
                                        FormView)
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import (reverse_lazy,
                            reverse)
from django.http.response import HttpResponseRedirect

from .forms import (DiarioForm,
                    EditarAlimentoForm)
from .models import (Alimento,
                    AlimentoConsumido)
from applications.diario.models import Diario

from .functions import (cal_x_gramo,
                        total_cal,
                        limpiar_lista)
from .serializers import AlimentoSerializer,AlimentoConsumidoSerializer
from .filters import AlimentoFilter



# Create your views here.

class BuscarAlimentos(LoginRequiredMixin,FormView,ListView):
    form_class=DiarioForm
    template_name="alimentos/buscar_alimento.html"
    filterset_class=AlimentoFilter
    #volver a detalle diario
    success_url=reverse_lazy('diario_urls:detallediario')

    #listview
    model = Alimento
    paginate_by=4
    ordering='nombre'
    context_object_name="alimentos"

    
    def get_queryset(self):
        #busqueda=self.request.GET.get('busqueda')
        diario_pk=self.kwargs['pk']
        diario=Diario.objects.get(pk=diario_pk)
        tipomascota=diario.mascota.tipo
        print('tipo mascota = %s' %tipomascota)
        query=Alimento.objects.all().filter(tipo_mascota=tipomascota)


        """if not busqueda:
            busqueda=""
        resultado=Alimento.objects.buscar_alimentos(busqueda).filter(tipo_mascota=tipomascota)
        return resultado"""

        # Then use the query parameters and the queryset to
        # instantiate a filterset and save it as an attribute
        # on the view instance for later.
        self.filterset = self.filterset_class(self.request.GET, queryset=query)
        # Return the filtered queryset
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        diario_pk=self.kwargs['pk']
        context["diario"]=Diario.objects.get(pk=diario_pk)

        # Pass the filterset to the template - it provides the form.
        context['filterset'] = self.filterset
        return context

    def form_valid(self, form):
        #objetos
        alimentos =limpiar_lista(self.request.POST.getlist('cb_alimento'))   

        #preciso objetos diario y alimento para poder insertarlo en la db
        diarioid=self.kwargs['pk']
        diario_obj=Diario.objects.get(pk=diarioid)
        self.pk=diarioid

        cantidad_clean=limpiar_lista(self.request.POST.getlist('cantidad'))
        print (cantidad_clean)


        #calculos auxiliares
        #listas clean
        #obtener las calorias de cada alimento chequeado
        lista_obj_alimentos,lista_cal_gramo_alimentos=cal_x_gramo(alimentos)
        lista_total_cal=total_cal(cantidad_clean,lista_cal_gramo_alimentos)

        alimentosConsumidos=[]

   
        if ((len(cantidad_clean)) == (len(lista_obj_alimentos))):

            for i in (range(len(alimentos))):
                alimentoconsumido=AlimentoConsumido(
                    alimento=lista_obj_alimentos[i],
                    diario=diario_obj,
                    cantidad=cantidad_clean[i],
                    total_cal=lista_total_cal[i],
                )
                alimentosConsumidos.append(alimentoconsumido)
            
            for i in range(len(alimentos)):
                diario_obj.total_cal+=lista_total_cal[i]
                diario_obj.save()

            AlimentoConsumido.objects.bulk_create(
            alimentosConsumidos
            )

            if (len(lista_obj_alimentos))==1:

                messages.success(self.request,"El alimento ha sido agregado con exito")
            else:
                messages.success(self.request,"Los alimentos han sido agregados con exito")

        else:
            #print('algo vino vacio o hay alguna diferencia en el largo')
            #print(len(cantidad_clean))
            #print(len(lista_obj_alimentos))
            messages.warning(self.request,"Para agregar los elementos debe completar todos sus campos!")
        
        return super(BuscarAlimentos, self).form_valid(form)

    def get_success_url(self):
         return reverse('diario_urls:detallediario', kwargs={'pk': self.pk})

class ListaAlimentos(LoginRequiredMixin,ListView):
    #detail view
    template_name="alimentos/lista_alimentos.html"
    context_object_name="alimentos"
    paginate_by=5
    ordering='nombre'
    model=Alimento

    def get_queryset(self):
        return Alimento.objects.buscar_alimentos_creadopor(self.request.user).order_by('nombre')


class AgregarAlimento(LoginRequiredMixin,CreateView):
    template_name="alimentos/agregar_alimento.html"
    model=Alimento
    fields=['nombre','marca','descripcion','calorias','tipo_mascota']
    success_url=reverse_lazy('alimentos_urls:listaalimentos')

    def form_valid(self, form):
        print('###FORM VALID###')
        print(self.request.user)
        alimento=form.save(commit=False)
        alimento.creada_por=self.request.user
        alimento.save()
        return super(AgregarAlimento,self).form_valid(form)

class BorrarAlimento(LoginRequiredMixin,TemplateView):
    #model=Alimento
    template_name="alimentos/eliminar_alimento.html"
    #success_url=reverse_lazy('alimentos_urls:listaalimentos')

    def dispatch(self, request, *args, **kwargs):
        #solo dueño puede eliminar alimento suyo
        alimento=Alimento.objects.get(pk=self.kwargs['pk'])

        if alimento.creada_por != self.request.user:
            messages.warning(self.request, 'Que hacemos metiendo mano en la url ?')
            return HttpResponseRedirect(reverse('alimentos_urls:listaalimentos'))
            #messages.success(self.request, 'Bienvenido!')

        return super(BorrarAlimento, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args,**kwargs):
        print('##GET eliminaralimentousuario##')
        alimento=Alimento.objects.get(pk=self.kwargs['pk'])
        #guardo el id del diario en una variable ya que voy a borrar el alimento de la db

        if alimento:
            alimento.delete()
            print('borrado')
            return HttpResponseRedirect(reverse('alimentos_urls:listaalimentos'))

        return super(BorrarAlimento,self).get(request, *args, **kwargs)
    

class EditarAlimento(LoginRequiredMixin,FormView):
    template_name="alimentos/editar_alimento.html"
    form_class=EditarAlimentoForm
    
    success_url=reverse_lazy('alimentos_urls:listaalimentos')

    def dispatch(self, request, *args, **kwargs):
        #solo dueño puede editar alimento del diario de su mascota
        alimento=Alimento.objects.get(pk=self.kwargs['pk'])


        if alimento.creada_por != self.request.user:
            messages.warning(self.request, 'Que hacemos metiendo mano en la url ?')
            return HttpResponseRedirect(reverse('alimentos_urls:listaalimentos'))
            #messages.success(self.request, 'Bienvenido!')

        return super(EditarAlimento, self).dispatch(request, *args, **kwargs)



    def form_valid(self, form):
        alimento=Alimento.objects.get(pk=self.kwargs['pk'])
        
        #update
        print("##POST editar alimento usuario##")

        if form.cleaned_data['nombre'] == alimento.nombre:
            print ('son iguales')
        else:
            print('no lo son, es {} y el form es {}'.format(alimento.nombre,form.cleaned_data['nombre']))
            alimento.nombre=form.cleaned_data['nombre']
            alimento.save()
        
        if form.cleaned_data['marca'] == alimento.marca:
            print ('son iguales')
        else:
            print('no lo son, es {} y el form es {}'.format(alimento.marca,form.cleaned_data['marca']))
            alimento.marca=form.cleaned_data['marca']
            alimento.save()
        
        if form.cleaned_data['descripcion'] == alimento.descripcion:
            print ('son iguales')
        else:
            print('no lo son, es {} y el form es {}'.format(alimento.descripcion,form.cleaned_data['descripcion']))
            alimento.descripcion=form.cleaned_data['descripcion']
            alimento.save()
        
        if form.cleaned_data['calorias'] == alimento.calorias:
            print ('son iguales')
        else:
            print('no lo son, es {} y el form es {}'.format(alimento.calorias,form.cleaned_data['calorias']))
            alimento.calorias=form.cleaned_data['calorias']
            alimento.save()
        

        return super(EditarAlimento,self).form_valid(form)
    
    """def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #comida=AlimentoConsumido.objects.get(pk=self.kwargs['pk'])
        comida=Alimento.objects.get(pk=self.kwargs['pk'])
        self.pk=comida.diario.id
        context['diario'] =Diario.objects.get(pk=self.pk) 
        return context"""
    #que hacía esto? solo un hechicero podría saberlo
    
    #sobreescribimos el metodo para obtener los kwargs del form para poder pasar la id al modelform
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['pk'] = self.kwargs['pk']
        return kwargs
    
    

    def get_success_url(self):
         return reverse('alimentos_urls:listaalimentos')


"APIS"

#Alimento
class BuscarAlimentoListApiView(ListAPIView):
    serializer_class=AlimentoSerializer

    def get_queryset(self):
        kword=self.request.query_params.get('kword','')

        return Alimento.objects.filter(
            nombre__icontains=kword
        ).order_by('nombre')

#ALimento Consumido

class AlimentoConsumidoListApiView(ListAPIView):

dam/templates/alimentos/agregar_alimento.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Agregar alimento{% endblock title %}

{% block content %}
<br>


<div class="container tm-mt-big tm-mb-big">
  <div class="row">
    <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
      <div class="tm-bg-primary-dark tm-block tm-block-h-auto">

        <div class="row">
          <div class="col-12">
            <h2 class="tm-block-title d-inline-block">Agregar alimento</h2>
          </div>
        </div>
        
        <div class="row tm-edit-product-row">
          <div class="col-xl-6 col-lg-6 col-md-12">

            <form action="" method="post" class="tm-edit-product-form">

              {% csrf_token %}
              {{ form|crispy }}

               <div class="col-12">
                   <button type="submit" class="btn btn-primary btn-block text-uppercase">Guardar</button>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

dam/templates/alimentos/buscar_alimento.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}
{% load i18n %}

{% block title %}Agregar alimento{% endblock title %}

{% block content %}
    <br>
    {% language 'es' %}
    <p class="h5">Agregar alimentos al diario del {{ diario.fecha }}</p>
    {% endlanguage %}


  <form action="" method="get">
    {{ filterset.form.as_p }}
    <button class="btn-sm btn-primary  text-uppercase mt-5"  type="submit">Buscar</button>
  </form>
  <br>

<form method="POST" name="alimentosform">
    {% csrf_token %}

<!--table prueba-->

<div class="col-sm-12 col-md-12 col-lg-8 col-xl-12 tm-block-col">
  <div class="tm-bg-primary-dark tm-block tm-block-products">
    <div class="tm-product-table-container">
      <table class="table table-hover tm-table-small tm-product-table mb-2">
        <thead>
          <tr>
              
            <th scope="col">&nbsp;</th>
            <th scope="col">Nombre</th>
            <th scope="col">Marca</th>
            <th scope="col">Calorias</th>
            <th scope="col"></th>

          </tr>
        </thead>
        <tbody>

          {% for i in alimentos  %}
          <tr>
            <th scope="row">
              <input title='Marque para agregar' type="checkbox" class="checkbox-{{ forloop.counter }}" 
              name="cb_alimento" id="cb_alimento-{{ forloop.counter }}" 
              value="{{ i.id }}" /> 
            </th>
            <td class="tm-product-name">{{ i.nombre }}</td>
            <td>{{ i.marca }}</td>
            <td >{{ i.calorias }}</td>
            
            <td>

              <input title='Ingrese la cantidad en gramos' 
              type="number"
              placeholder="Cantidad" 
              name="cantidad" 
              id="cantidad" 
              min="1" 
              oninput="this.value = 
             !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null">
           
            </td>

          </tr>
          {% empty %}
              No se han encontrado alimentos
          {% endfor %}
        </tbody>
      </table>
    </div>

      {% if is_paginated %}
        {% if page_obj.has_previous %}
        <a href="?{% param_replace page=1 %}">Primera</a>
          {% if page_obj.previous_page_number != 1 %}
            <a href="?{% param_replace page=page_obj.previous_page_number %}">Anterior</a>
          {% endif %}
        {% endif %}

        Pagina {{ page_obj.number }} de {{ paginator.num_pages }}

        {% if page_obj.has_next %}
          {% if page_obj.next_page_number != paginator.num_pages %}
            <a href="?{% param_replace page=page_obj.next_page_number %}">Siguiente</a>
          {% endif %}
          <a href="?{% param_replace page=paginator.num_pages %}">Ultima</a>
        {% endif %}

        <p>Resultados {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>
      {% endif %}


    <!-- table container -->
    <button class="btn btn-primary  text-uppercase mt-2 mb-5"  type="submit" >Agregar seleccionado</button>
  </div>
</div>

<!-- fin table prueba-->

</form>

{% endblock content %}

{% block js %}

<script type="text/javascript" src="{% static 'vue/vue.js' %}">  </script>
<script type="text/javascript"  src="{% static 'vue/axios.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vue/apps/buscarAlimento.js' %}">  </script>

{% endblock js %}

dam/templates/alimentos/editar_alimento.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Editar alimento{% endblock title %}

{% block content %}

    <br>

    <div class="container tm-mt-big tm-mb-big">
        <div class="row">
          <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
            <div class="tm-bg-primary-dark tm-block tm-block-h-auto">

              <div class="row">
                <div class="col-12">
                  <h2 class="tm-block-title d-inline-block">Editar alimento</h2>
                </div>
              </div>
              
              <div class="row tm-edit-product-row">
                <div class="col-xl-6 col-lg-6 col-md-12">

                  <form action="" method="post" class="tm-edit-product-form">

                    {% csrf_token %}
                    {{ form|crispy }}

                     <div class="col-12">
                         <button type="submit" class="btn btn-primary btn-block text-uppercase">Guardar</button>
                    </div>

                  </form>

                </div>
              </div>

            </div>
          </div>
        </div>
      </div>





{% endblock content %}

dam/templates/alimentos/eliminar_alimento.html
{% extends 'base.html' %}
{% block title %}Eliminar alimento{% endblock title %}

{% block navbar_secundaria %}

{% endblock navbar_secundaria %}

{% block content %}

    <h1>¿Estas seguro de eliminar este alimento ?</h1>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
    </form>
{% endblock content %}

dam/templates/alimentos/lista_alimentos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Lista alimentos{% endblock title %}
{% block navbar_secundaria %}
{% endblock navbar_secundaria %}

{% block content %}

<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-auto mb-3">
        
{% if messages %}
  {% for message in messages  %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
      <br>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>
             <p class="text-center"> {{ message }}</p>
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
             <p class="text-center"> {{ message }}</p>
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} 
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
             <p class="text-center"> {{ message }}</p>
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

  {% endfor %}
{% endif %}
        </div>
    </div>
</div>

<div class="col-sm-12 col-md-12 col-lg-8 col-xl-12 tm-block-col">
    <div class="tm-bg-primary-dark tm-block tm-block-products">
      <div class="tm-product-table-container">
        <table class="table table-hover tm-table-small tm-product-table">
          <thead>
            <tr>
                
              <th scope="col">&nbsp;</th>
              <th scope="col">Nombre</th>
              <th scope="col">Marca</th>
              <th scope="col">Calorías (Kg)</th>
              <th scope="col"></th>
              <th scope="col"></th>
              
              
            </tr>
          </thead>
          <tbody>

            {% for i in alimentos  %}
            <tr>
              <th scope="row"><!--<input type="checkbox" />--></th>
              <td class="tm-product-name">{{ i.nombre }}</td>
              <td>{{ i.marca }}</td>
              <td >{{ i.calorias }}</td>
              
              <td>
                <a title="Editar" href="{% url 'alimentos_urls:editaralimento' i.id %}">
                 <img src="{% static 'iconos/modificar.svg' %}" width="18" height="24" alt="icono-editar">
                </a>
              </td>
              <td>
                <a title="Borrar" href="{% url 'alimentos_urls:eliminaralimento' i.id %}">                 
                 <img src="{% static 'iconos/eliminar.svg' %}" width="18" height="24" alt="icono-eliminar">
                </a>
              </td>
            </tr>
            {% empty %}
                Todaviía no has cargado ningún alimento
            {% endfor %}

          </tbody>
        </table>
      </div>
      <!-- table container -->
      <a 
      href="{% url 'alimentos_urls:agregaralimento' %}" class="btn btn-primary btn-block text-uppercase mt-5">
      Agregar nuevo alimento
     </a>

     <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            {% if is_paginated %}
                <nav aria-label="123">
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Atras</a></li>
                        {% endif %}
    
                        {% for pagina in paginator.page_range  %}
                        {% if pagina == page_obj.number %}
    
                        <li class="page-item active"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a></li>
    
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a></li>
    
                        {% endif %}
                        
                        {% endfor %}
    
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div> 
    </div>
    </div>
  </div>

{% endblock content %}