dam/applications/diario/urls.py
from django.urls import path

from .views import (
                    VerDiarios,
                    EditarAlimentoDiario,
                    EliminarAlimentoDiario,
                    DetalleDiario,
                    BuscarDiarioApiView
                    )


app_name="diario_urls"

urlpatterns = [
    #path('mostrar/',,name="mostrar-mascotas"),
    path('ver-diarios/<pk>/',VerDiarios.as_view(),name="verdiario"),
    path('detalle-diario/<pk>/',DetalleDiario.as_view(),name="detallediario"),
    path('editar-alimento/<pk>/',EditarAlimentoDiario.as_view(),name="editalimento"),
    path('eliminar-alimento/<pk>/',EliminarAlimentoDiario.as_view(),name="eliminaralimento"),
    path('api/diarios/buscar/',BuscarDiarioApiView.as_view(),name="buscardiario"),

]

dam/applications/mascotas/urls.py
from django.urls import path
from .views import (MascotaRegisterView,
                    ListarMascotasView,
                    UpdateMascotaView,
                    DeleteMascotaView,
                    PanelMascotaView,
                    ReportesMascotaView,
                    AgregarNotaView,
                    PerfilMascotaView,
                    listresults,
                    borrarnota,
                    BuscarMascotaApiView)

app_name="mascotas_urls"

urlpatterns = [
    path('registrar/',MascotaRegisterView.as_view(),name="registrarmascota"),
    path('listar-mascotas/',ListarMascotasView.as_view(),name="listarmascotas"),
    path('editar/<int:pk>/',UpdateMascotaView.as_view(),name="editar"),
    path('panel-mascota/<int:pk>/',PanelMascotaView.as_view(),name="panelmascota"),
    path('eliminar-mascotas/<int:pk>/',DeleteMascotaView.as_view(),name="delete"),
    path('reportes-mascotas/<int:pk>/',ReportesMascotaView.as_view(),name="reportes"),
    path('notas-mascotas/<int:pk>/',AgregarNotaView.as_view(),name="notas"),
    path('perfil-mascota/<int:pk>/',PerfilMascotaView.as_view(),name="perfil"),
    path('descargar/<int:pk>/',listresults,name="descargar"),
    path('borrar-nota/<int:pk>/',borrarnota,name="borrarnota"),
    #api
    path('api/mascota/buscar/',BuscarMascotaApiView.as_view(),name="buscarmascota"),

]

dam/dam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from applications.users.views import Index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/',include('applications.users.urls')),
    path('mascotas/',include('applications.mascotas.urls')),
    path('alimentos/',include('applications.alimentos.urls')),
    path('diario/',include('applications.diario.urls',namespace='diaro_urls')),
    path('',Index.as_view(),name="index")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dam/applications/mascotas/views.py
from datetime import datetime, timedelta

from rest_framework.generics import ListAPIView

from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

from django.views.generic.list import ListView

from django.http import HttpResponseRedirect

import django_excel as excel

from django.contrib import messages
from django.views.generic import (
                                ListView,
                                DeleteView,
                                TemplateView
                                )
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy,reverse


from applications.diario.models import Diario
from .forms import (
                    MascotaRegisterForm,
                    MascotaUpdateForm,
                    AgregarNotaForm,
                    )
from .models import (
                    Mascota,
                    PesoMascotaDiario,
                    Nota
                    )
from .functions import generar_grafico
from .filters import NotaFilter
from .serializers import MascotaSerializer

# Create your views here.

#preciso estar logueado para añadir mascota


class MascotaRegisterView(LoginRequiredMixin,FormView):
    template_name="mascotas/registrar.html"
    form_class=MascotaRegisterForm
    success_url=reverse_lazy('mascotas_urls:listarmascotas')

    def form_valid(self, form):
        dueño=self.request.user
        nombre=form.cleaned_data['nombre']
        tipo=form.cleaned_data['tipo']
        edad=int(form.cleaned_data['edad'])
        peso=form.cleaned_data['peso']
        actividad=form.cleaned_data['actividad']
        tamaño=form.cleaned_data['tamaño']
        esterilizado=form.cleaned_data['esterilizado']
        objetivo=form.cleaned_data['objetivo']
        imagen=form.cleaned_data['imagen']

        
        Mascota.objects.create_mascota(
            
            dueño=dueño,
            nombre=nombre,
            tipo=tipo,
            edad=edad,
            peso=peso,
            actividad=actividad,
            tamaño=tamaño,
            esterilizado=esterilizado,
            objetivo=objetivo,
            imagen=imagen,
        )
        
        return super(MascotaRegisterView,self).form_valid(form)

class PanelMascotaView(LoginRequiredMixin,TemplateView):
    template_name="mascotas/panel.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mascota'] =Mascota.objects.get(pk=self.kwargs['pk']) 
        return context
    
class ListarMascotasView(LoginRequiredMixin,ListView):
    template_name ="mascotas/listarmascotas.html"
    model = Mascota
    paginate_by=3
    ordering='nombre'
    context_object_name='lista_mascotas'
    

    def get_queryset(self):
        
        return Mascota.objects.buscar_mascota_dueñoid(self.request.user.id).order_by('nombre')


class UpdateMascotaView(LoginRequiredMixin,FormView):
    template_name="mascotas/editar.html"
    form_class=MascotaUpdateForm
    success_url=reverse_lazy('mascotas_urls:listarmascotas')


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['pk'] = self.kwargs['pk']
        return kwargs

    def form_valid(self, form):
        mascota=Mascota.objects.get(pk=self.kwargs['pk'])

        nombre=form.cleaned_data['nombre']
        tipo=form.cleaned_data['tipo']
        edad=form.cleaned_data['edad']
        peso=form.cleaned_data['peso']
        actividad=form.cleaned_data['actividad']
        tamaño=form.cleaned_data['tamaño']
        esterilizado=form.cleaned_data['esterilizado']
        objetivo=form.cleaned_data['objetivo']
        imagen=form.cleaned_data['imagen']

        if nombre!=mascota.nombre:
            print('campo nombre con diferencias')
            mascota.nombre=nombre
            messages.success(self.request, 'Nombre cambiado con exito!')

        if tipo!=mascota.tipo:
            print('campo tipo con diferencias')
            mascota.tipo=tipo
            messages.success(self.request, 'Tipo de mascota cambiado con exito!')

        if edad!=mascota.edad:
            print('campo edad con diferencias')
            mascota.edad=edad
            messages.success(self.request, 'Edad cambiado con exito!')

        if peso!=mascota.peso:
            print('campo peso con diferencias')
            mascota.peso=peso
            messages.success(self.request, 'Peso cambiado con exito!')

        if actividad!=mascota.actividad:
            print('campo actividad con diferencias')
            mascota.actividad=actividad
            messages.success(self.request, 'Actividad cambiada con exito!')

        if tamaño!=mascota.tamaño:
            print('campo tamaño con diferencias')
            mascota.tamaño=tamaño
            messages.success(self.request, 'Tamaño cambiado con exito!')

        if esterilizado!=mascota.esterilizado:
            print('campo esterilizado con diferencias')
            mascota.esterilizado=esterilizado
            messages.success(self.request, 'Esterilizado cambiado con exito!')

        if objetivo!=mascota.objetivo:
            print('campo objetivo con diferencias')
            mascota.objetivo=objetivo
            messages.success(self.request, 'Objetivo cambiado con exito!')
        
        if imagen:
            print('imagen cambiada')
            mascota.imagen=imagen
            messages.success(self.request, 'Imagen cambiada con exito!')

        
        mascota.save()


        
        
        return super(UpdateMascotaView,self).form_valid(form)

class DeleteMascotaView(LoginRequiredMixin,DeleteView):
    template_name="mascotas/eliminar.html"
    model=Mascota
    success_url=reverse_lazy('mascotas_urls:listarmascotas')

class ReportesMascotaView(LoginRequiredMixin,TemplateView):
    template_name="mascotas/reportes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        mascota=Mascota.objects.get(pk=self.kwargs['pk'])
        context['mascota'] =mascota

        dias=7
        tipografico=self.request.GET.get('selectTipo')
        print(tipografico)

        if (self.request.GET.get('selectDias') != None):
            dias=int(self.request.GET.get('selectDias'))
            

        if tipografico=="calorias":
            if dias != None:
                graph_div=generar_grafico(mascota,tipografico,dias)
                context["graph_div"]=graph_div

        elif tipografico=="peso":
            if dias != None:
                graph_div=generar_grafico(mascota,tipografico,dias)
                context["graph_div"]=graph_div

        return context
    
# generar el reporte en memoria y devolverlo a traves de una http response
def listresults(request,pk):
    
    tipografico=request.POST.get('selectTipo','')
    cantdias=int(request.POST.get('selectDias',''))
    formato=request.POST.get('selectFormato','')
    mascota=Mascota.objects.get(pk=pk)

    print('tipo de grafico {}, cantidad dias {}, formato: {}'.format(tipografico,cantdias,formato))

    # Definir los datos en una lista
    export = [] 

    if tipografico=='calorias':
        # Se obtienen los datos del model y se agregan a la lista
        diarios=Diario.objects.filter(mascota=mascota,fecha__gte=datetime.now()-timedelta(days=cantdias)).order_by('fecha')
        if diarios:
            export.append(['Fecha', 'Calorias'])
            #formateamos la fecha al estilo "25-09-1996"
            for diario in diarios:
                export.append(["{0:%d-%m-%Y}".format(diario.fecha), diario.total_cal])
                

    if tipografico=='peso':
        pesos=PesoMascotaDiario.objects.filter(mascota=mascota,fecha__gte=datetime.now()-timedelta(days=cantdias)).order_by('fecha')
        if pesos:
            export.append(['Fecha', 'Peso (kg)'])
            #formateamos la fecha al estilo "25-09-1996"
            for i in pesos:
                export.append(["{0:%d-%m-%Y}".format(i.fecha),float(i.peso)])

    #obtenemos la fecha de hoy para añadirla al archivo

    fechahoy    = datetime.now()
    strFechahoy = fechahoy.strftime("%d%m%Y")
    
    # Transcribir la data a una hoja de calculo en memoria
    sheet = excel.pe.Sheet(export)

    # Generar el archivo desde la hoja en memoria con 
    # un nombre de archivo que se recibira en el navegador

    if formato == "csv":
        return excel.make_response(sheet, "csv", file_name="Reporte-"+strFechahoy+".csv")
    elif formato == "ods":
        return excel.make_response(sheet, "ods", file_name="Reporte-"+strFechahoy+".ods")
    elif formato == "xlsx":
        return excel.make_response(sheet, "xlsx", file_name="Reporte-"+strFechahoy+".xlsx")
    else:
        messages.warning(request, 'formato {} no soportado'.format(formato))


class AgregarNotaView(LoginRequiredMixin,FormView):
    template_name="mascotas/notas.html"
    form_class=AgregarNotaForm

    def form_valid(self, form):
        mascota_id=self.kwargs['pk']
        
        mascota=Mascota.objects.get(pk=mascota_id)
        print('mascota id {}, mascota : {}'.format(mascota_id,mascota))

        fecha=form.cleaned_data['fecha']
        importancia=form.cleaned_data['importancia']
        texto=form.cleaned_data['texto']

        print('fecha: {} importancia {} texto {}'.format(fecha,importancia,texto))

        Nota.objects.create(
            mascota=mascota,
            fecha=fecha,
            importancia=importancia,
            texto=texto

        )

        return HttpResponseRedirect(
            reverse(
                'mascotas_urls:perfil',
                kwargs={'pk': mascota_id}
            )
        )
    
    

class PerfilMascotaView(LoginRequiredMixin,ListView):
    template_name ="mascotas/perfilmascota.html"
    filterset_class=NotaFilter
    paginate_by=3
    context_object_name='notas'
    #ordering='-fecha'

dam/templates/mascotas/editar.html
{% extends 'base.html' %}
{% block title %}Editar mascota{% endblock title %}


{% load crispy_forms_tags %}

{% block content %}

<div class="container tm-mt-big tm-mb-big">
    <div class="row">
      <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
        <div class="tm-bg-primary-dark tm-block tm-block-h-auto">

          <div class="row">
            <div class="col-12">
              <h2 class="tm-block-title d-inline-block">Editar mascota</h2>
            </div>
          </div>
          
          <div class="row tm-edit-product-row">
            <div class="col-xl-6 col-lg-6 col-md-12">

              <form action="" method="post" class="tm-edit-product-form" enctype='multipart/form-data'>

                {% csrf_token %}
                {{ form|crispy }}

                 <div class="col-12">
                     <button type="submit" class="btn btn-primary btn-block text-uppercase">Guardar</button>
                </div>

              </form>

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

{% endblock content %}

dam/templates/mascotas/eliminar.html
{% extends 'base.html' %}
{% block title %}Eliminar mascota{% endblock title %}


{% block content %}
    <h1>¿Estas seguro de eliminar esta mascota ?</h1>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
    </form>
{% endblock content %}

    

dam/templates/mascotas/listarmascotas.html
{% extends 'base.html' %}
{% block title %}Lista mascotas{% endblock title %}


{% block content %}

{% if messages %}
  {% for message in messages  %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
      <br>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %} 

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} 
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

  {% endfor %}
{% endif %}





<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <p class="h4">Estas son tu mascotas {{ user.username }} </p>
    </div>
</div>

<div class="container-fluid mt-4">
    <div class="row justify-content-center">

        {% for i in lista_mascotas  %}

            <div class="col-auto mb-3">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.nombre }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ i.tipo }}</h6>
                        <p class="card-text">
                        </p>
                        <a href="{% url 'mascotas_urls:perfil' i.id %}" class="btn btn-primary ">Perfil</a>
                    </div>
                </div>
            </div>
        {% empty %}
        <p>No tenes mascotas, registra una</p>

        {% endfor %}

    
    </div>

    <div class="row justify-content-center">

        {% if is_paginated %}
            <nav aria-label="123">
                <ul class="pagination pagination-sm">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Atras</a></li>
                    {% endif %}

                    {% for pagina in paginator.page_range  %}
                    {% if pagina == page_obj.number %}

                    <li class="page-item active"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a></li>

                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a></li>

                    {% endif %}
                    
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}

    </div>
    
</div>

{% endblock content %}

dam/templates/mascotas/panel.html
{% extends 'base.html' %}
{% block title %}Panel mascotas{% endblock title %}


{% block content %}
    <p class="h1">Panel de {{ mascota.nombre }}</p>
    <br>
    
    <div class="list-group">
        <a href="{% url 'mascotas_urls:editar' pk=mascota.id %}" class="list-group-item list-group-item-action">Editar</a>
        <a href="{% url 'mascotas_urls:delete' pk=mascota.id %}" class="list-group-item list-group-item-action">Borrar</a>
    </div>

{% endblock content %}

dam/templates/mascotas/perfilmascota.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}
{% block title %}Perfil{% endblock title %}

{% block content %}

{% if messages %}
  {% for message in messages  %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
      <br>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %} 

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} 
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

  {% endfor %}
{% endif %}

<div class="container mt-5">
   
    <!-- row -->
    <div class="row tm-content-row">
        
      <div class="tm-block-col tm-col-avatar">
        <div class="tm-bg-primary-dark tm-block tm-block-avatar">
          <h2 class="tm-block-title">Perfil </h2>
          
          
          <div class="tm-avatar-container">
            {% if mascota.imagen  %}
            <img
              src="{{mascota.imagen.url}}"
              alt="Avatar"
              class="tm-avatar img-fluid mb-4"
            />
            {% else %}
            <img
              src="https://bootdey.com/img/Content/avatar/avatar3.png"
              alt="Avatar"
              class="tm-avatar img-fluid mb-4"
            />
            {% endif %}

          </div>

          <a class="btn btn-primary btn-block text-uppercase" 
          href="{% url 'diario_urls:verdiario' mascota.id %}">
              Diario
          </a>

          <a class="btn btn-primary btn-block text-uppercase" 
          href="{% url 'mascotas_urls:panelmascota' mascota.id %}">
          Panel
         </a>

          <a class="btn btn-primary btn-block text-uppercase" 
          href="{% url 'mascotas_urls:reportes' mascota.id %}">
          Reportes
         </a>

          <a class="btn btn-primary btn-block text-uppercase" 
          href="{% url 'mascotas_urls:notas' mascota.id %}">
          Agregar nota
         </a>
          
        </div>
      </div>
      
      <div class="tm-block-col tm-col-account-settings">
        <div class="tm-bg-primary-dark tm-block tm-block-settings">
          <h2 class="tm-block-title">Información</h2>

            <div class="form-group col-lg-6">
              <label for="name">
                  Nombre 
                  {{ mascota.nombre }}
              </label> 
            </div>

            <div class="form-group col-lg-6">
                <label for="name">
                    Tamaño 
                    {{ mascota.tamaño }}
                </label> 
            </div>

            <div class="form-group col-lg-6">
                <label for="name">
                    Edad 
                    {{ mascota.edad }}
                    Meses
                </label> 
            </div>
            
            <div class="form-group col-lg-6">
                <label for="name">
                    Peso 
                    {{ mascota.peso }}
                    Kg
                </label> 
            </div>

            <div class="form-group col-lg-6">
                <label for="name">
                    Actividad 
                    {{ mascota.actividad }}
                </label> 
            </div>

            <div class="form-group col-lg-6">
                <label for="name">
                    Meta diaria 
                    {{ mascota.meta }}
                    Calorías
                </label> 
            </div>

            <div class="form-group col-lg-6">
                <label for="name">
                    Objetivo 
                    {{ mascota.objetivo }}
                </label> 
            </div>
   
       
        </div>
      </div>

      <div class="tm-block-col tm-col-account-settings">
        <div class="tm-bg-primary-dark tm-block tm-block-settings">

             <p class="h4 mb-3"><strong>Notas</strong></p>
  <p class="h6">Ingrese la fecha de inicio y la fecha de fin</p>
  <form action="" method="get">
    {{ filterset.form.as_p }}
    
    <button class="btn-sm btn-primary text-uppercase"   type="submit">Buscar</button>
  </form>


<div id="accordion">
<br>


    {% if notas %}
  
    Aqui estan sus notas:
    <br>
    



        {% for object in object_list  %}
        
            <div class="card mt-3 mb-4 ">
                <!--para cambiarle los colores a las cabeceras de las notas -->

                    {% if object.importancia == "Normal" %}
                        <div class="card-header p-3 mb-2 bg-primary " id="headingOne">
                    {% elif object.importancia == "Moderada" %}
                        <div class="card-header p-3 mb-2 bg-warning text-dark" id="headingOne">
                    {% elif object.importancia == "Alta" %}
                        <div class="card-header p-3 mb-2 bg-danger text-dark" id="headingOne">
                    
                {% endif %} 
                <h5 class="mb-0">
                    <button class="btn" data-toggle="collapse" data-target="#collapse{{forloop.counter}}" 
                    aria-expanded="true" aria-controls="collapseOne">
                    {{ object.fecha }} <a title="Borrar" href="{% url 'mascotas_urls:borrarnota' object.id  %}">
                   
                    </button>
                     <img src="{% static 'iconos/cesto.svg' %}" title="Archivar" width="18" height="18">
                    </a>
                </h5>
                </div>

                <div id="collapse{{forloop.counter}}" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                    <div class="card-body">

                        {% if object.importancia == "Normal" %}
                            <p class="text-primary">{{ object.texto }}</p>
                        {% elif object.importancia == "Moderada" %}
                            <p class="text-warning">{{ object.texto }}</p>
                        {% elif object.importancia == "Alta" %}
                            <p class="text-danger">{{ object.texto }}</p>
                        {% endif %} 

                        
                    </div>
                </div>
            </div>
        
        {% endfor %}

        {% if is_paginated %}
            <nav aria-label="123">
                <ul class="pagination pagination-sm mt-3">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">Primera</a></li>
                    {% if page_obj.previous_page_number != 1 %}
                <li class="page-item">
                <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">Atras</a></li>
                    {% endif %}
                {% endif %}

            

            {% if page_obj.has_next %}
                {% if page_obj.next_page_number != paginator.num_pages %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">Siguiente</a></li>
                {% endif %}
                <li class="page-item">
                <a class="page-link" href="?{% param_replace page=paginator.num_pages %}">Ultima</a></li>
            {% endif %}

            <!--<p>Objects {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>-->
                </ul>
            </nav>
        {% endif %}


    {% else %}
    No hay notas

    {% endif %}
   
       
        </div>
      </div>
      
    </div>
  </div>


  </div>
</div>




{% endblock content %}

dam/templates/mascotas/reportes.html
{% extends 'base.html' %}
{% block title %}Reportes{% endblock title %}
{% block content %}


{% if messages %}
  {% for message in messages  %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
      <br>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %} 

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} 
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

  {% endfor %}
{% endif %}


<div class="container-fluid mt-4">
    <div class="row justify-content-start">
        <div class="col-auto mb-3">
            <p class="h4">Reportes de {{ mascota.nombre }}</p>

            <form  method="GET">

                <div class="form-group">
                    <label for="selectTipo">Elija una opcion: </label>
                    <select name="selectTipo" id="selectTipo">
                    <option value="calorias">Calorias</option>
                    <option value="peso">Peso</option>
                    </select>
                </div>

                <p class="h4">Dias: </p>
                <div class="form-group">
                    <select  name="selectDias" id="selectDias">
                    <option value="7">7</option>
                    <option value="15">15</option>
                    <option value="30">30</option>
                    <option value="60">60</option>
                    <option value="90">90</option>
                    </select>
                </div>

                <input class="btn btn-success" type="submit" value="Generar">

            </form>
        </div>
    </div>
</div>
       
    <div class="mb-4" style="width:1000;height:100">
        {{ graph_div|safe }}
    </div>

<div class="container-fluid mt-4">
    <div class="row justify-content-start">
        <div class="col-auto mb-3">
            <p class="h5">Descargar reporte de {{ mascota.nombre }}</p>

            <form  method="POST" action="{% url 'mascotas_urls:descargar' mascota.id  %}">
                {% csrf_token %}

            <div class="form-group">
                    <label for="selectTipo">Tipo de grafico </label>
                    <select  name="selectTipo" id="selectTipo">
                    <option value="calorias">Calorias</option>
                    <option value="peso">Peso</option>
                    </select>
                </div>

                <label for="selectDias">Cantidad de días </label>
                <div class="form-group">
                    <select  name="selectDias" id="selectDias">
                    <option value="7">7</option>
                    <option value="15">15</option>
                    <option value="30">30</option>
                    <option value="60">60</option>
                    <option value="90">90</option>
                    </select>
                </div>

                <label for="selectFormato">Formato </label>
                <div class="form-group">
                    <select name="selectFormato" id="selectFormato">
                    <option value="csv">Csv</option>
                    <option value="xlsx">Excel</option>
                    <option value="ods">LibreOffice</option>
                    </select>
                </div>

             <input class="btn-sm btn-success" type="submit" value="Descargar">

            </form>
        </div>
    </div>
</div>

{% endblock content %}