dam/applications/alimentos/urls.py
from django.urls import path
from .views import (
                    BuscarAlimentos,
                    ListaAlimentos,
                    AgregarAlimento,
                    BorrarAlimento,
                    EditarAlimento,
                    BuscarAlimentoListApiView,
                    AlimentoConsumidoListApiView,)

app_name="alimentos_urls"

urlpatterns = [
    path('listar-alimentos/<int:pk>/',BuscarAlimentos.as_view(),name="listar-alimentos"),
    path('lista-alimentos/',ListaAlimentos.as_view(),name="listaalimentos"),
    path('agregar-alimento/',AgregarAlimento.as_view(),name="agregaralimento"),
    path('eliminar-alimento/<int:pk>/',BorrarAlimento.as_view(),name="eliminaralimento"),
    path('editar-alimento/<int:pk>/',EditarAlimento.as_view(),name="editaralimento"),
    #apis
    path('api/alimentos/buscar/',BuscarAlimentoListApiView.as_view(),name="buscaralimentoapi"),
    path('api/alimentos-consumidos/buscar/',AlimentoConsumidoListApiView.as_view(),name="buscaralimentoconsumidoapi"),


]

dam/applications/diario/urls.py
from django.urls import path

from .views import (
                    VerDiarios,
                    EditarAlimentoDiario,
                    EliminarAlimentoDiario,
                    DetalleDiario,
                    BuscarDiarioApiView
                    )


app_name="diario_urls"

urlpatterns = [
    #path('mostrar/',,name="mostrar-mascotas"),
    path('ver-diarios/<pk>/',VerDiarios.as_view(),name="verdiario"),
    path('detalle-diario/<pk>/',DetalleDiario.as_view(),name="detallediario"),
    path('editar-alimento/<pk>/',EditarAlimentoDiario.as_view(),name="editalimento"),
    path('eliminar-alimento/<pk>/',EliminarAlimentoDiario.as_view(),name="eliminaralimento"),
    path('api/diarios/buscar/',BuscarDiarioApiView.as_view(),name="buscardiario"),

]

dam/applications/mascotas/urls.py
from django.urls import path
from .views import (MascotaRegisterView,
                    ListarMascotasView,
                    UpdateMascotaView,
                    DeleteMascotaView,
                    PanelMascotaView,
                    ReportesMascotaView,
                    AgregarNotaView,
                    PerfilMascotaView,
                    listresults,
                    borrarnota,
                    BuscarMascotaApiView)

app_name="mascotas_urls"

urlpatterns = [
    path('registrar/',MascotaRegisterView.as_view(),name="registrarmascota"),
    path('listar-mascotas/',ListarMascotasView.as_view(),name="listarmascotas"),
    path('editar/<int:pk>/',UpdateMascotaView.as_view(),name="editar"),
    path('panel-mascota/<int:pk>/',PanelMascotaView.as_view(),name="panelmascota"),
    path('eliminar-mascotas/<int:pk>/',DeleteMascotaView.as_view(),name="delete"),
    path('reportes-mascotas/<int:pk>/',ReportesMascotaView.as_view(),name="reportes"),
    path('notas-mascotas/<int:pk>/',AgregarNotaView.as_view(),name="notas"),
    path('perfil-mascota/<int:pk>/',PerfilMascotaView.as_view(),name="perfil"),
    path('descargar/<int:pk>/',listresults,name="descargar"),
    path('borrar-nota/<int:pk>/',borrarnota,name="borrarnota"),
    #api
    path('api/mascota/buscar/',BuscarMascotaApiView.as_view(),name="buscarmascota"),

]

dam/applications/users/urls.py
from django.urls import path
from .views import (
                    UserRegisterView,
                    LoginUser,
                    LogoutView,
                    HomePage,
                    CodeVerificationView,
                    ReestablecerPassView,
                    PanelUsuarioView,
                    BuscarDueñoApiView,
                    FaqView
                    )

app_name='users_app'

urlpatterns = [
    path('registrar/',UserRegisterView.as_view(),name="registraruser"),
    path('login/',LoginUser.as_view(),name="loginuser"),      
    path('logout/',LogoutView.as_view(),name="logoutuser"), 
    path('panel/',HomePage.as_view(),name="paneluser"),
    path('user-verificacion/<int:pk>/',CodeVerificationView.as_view(),name="userverificacion"),
    path('reestablecerpass/',ReestablecerPassView.as_view(),name="reestablecerpass"),
    path('panel-usuario/',PanelUsuarioView.as_view(),name="panelusuario"),
    path('faq',FaqView.as_view(),name="preguntasfrecuentes"),
    #api
    path('api/dueño/buscar/',BuscarDueñoApiView.as_view(),name="buscardueño"),
    

]

dam/dam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from applications.users.views import Index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/',include('applications.users.urls')),
    path('mascotas/',include('applications.mascotas.urls')),
    path('alimentos/',include('applications.alimentos.urls')),
    path('diario/',include('applications.diario.urls',namespace='diaro_urls')),
    path('',Index.as_view(),name="index")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dam/templates/includes/navbarbarmascdiarios.html
<div class="container-fluid">
    <div class="row justify-content-center">  

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #38B000;">
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <li class="nav-item">
          <a class="nav-link" href="{% url 'diario_urls:verdiario' pk=diario.mascota.id %}">Diario</a>
      </li>

       <!--
          <li class="nav-item">
            <a class="nav-link" href="{% url 'diario_urls:detallediario' pk=diario.id %}">Detalle diario</a>
          </li>
         -->

    </ul>

  </div>
</nav>

  </div>
</div>





                
               

dam/templates/includes/navbarmascotas.html
<div class="container-fluid">
    <div class="row justify-content-center">  
        <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #38B000;">
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
              
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'mascotas_urls:registrarmascota' %}"><strong>Registrar mascota</strong></a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'mascotas_urls:listarmascotas' %}"><strong>Ver mascotas</strong></a>
                </li>
                
                {% block navlinksmascota %} 

                {% endblock navlinksmascota %}  
               
              </ul>
            </div>
          </div>
        </nav>
  </div>
</div>

dam/templates/includes/navbarprincipal.html
{% load bootstrap_icons %}
<nav class="navbar navbar-expand-xl">
  <div class="container h-100">
      <a class="navbar-brand" >
          <h1 class="tm-site-title mb-0">DAM</h1>
      </a>
      <button class="navbar-toggler ml-auto mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars tm-nav-icon"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto h-100">

            {% if  user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  <span>
                      Alimentos
                  </span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'alimentos_urls:listaalimentos' %}">Mis alimentos</a>
                  <a class="dropdown-item"href="{% url 'alimentos_urls:agregaralimento' %}">Agregar</a>
              </div>
            </li>
              


              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false">
                      <span>
                          Mascotas
                      </span>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'mascotas_urls:listarmascotas' %}">Mis mascotas</a>
                      <a class="dropdown-item" href="{% url 'mascotas_urls:registrarmascota' %}">Registrar</a>
                  </div>
              </li>
              <li class="nav-item">

                  <a class="nav-link" href="{% url 'users_app:preguntasfrecuentes' %}">
                    FAQ
                  </a>

              </li>

              {% endif %}
          </ul>

        {% if not user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link d-block" href="{% url 'users_app:registraruser' %}">
                    <b>Registrarse</b>
                </a>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link d-block" href="{% url 'users_app:loginuser' %}">
                    <b>Acceder</b>
                </a>
            </li>
          </ul>
          {% endif %}
          
          {% if user.is_authenticated%}
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link d-block" href="{% url 'users_app:panelusuario' %}">
                    Bienvenido,{{ user.username }}
                  </a>
              </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link d-block" href="{% url 'users_app:logoutuser' %}">
                  <b>Salir</b>
                </a>
            </li>
        </ul>

          {% endif %}

      </div>
  </div>

</nav>