dam/applications/alimentos/urls.py
from django.urls import path
from .views import (
                    BuscarAlimentos,
                    ListaAlimentos,
                    AgregarAlimento,
                    BorrarAlimento,
                    EditarAlimento,
                    BuscarAlimentoListApiView,
                    AlimentoConsumidoListApiView,)

app_name="alimentos_urls"

urlpatterns = [
    path('listar-alimentos/<int:pk>/',BuscarAlimentos.as_view(),name="listar-alimentos"),
    path('lista-alimentos/',ListaAlimentos.as_view(),name="listaalimentos"),
    path('agregar-alimento/',AgregarAlimento.as_view(),name="agregaralimento"),
    path('eliminar-alimento/<int:pk>/',BorrarAlimento.as_view(),name="eliminaralimento"),
    path('editar-alimento/<int:pk>/',EditarAlimento.as_view(),name="editaralimento"),
    #apis
    path('api/alimentos/buscar/',BuscarAlimentoListApiView.as_view(),name="buscaralimentoapi"),
    path('api/alimentos-consumidos/buscar/',AlimentoConsumidoListApiView.as_view(),name="buscaralimentoconsumidoapi"),


]

dam/applications/diario/urls.py
from django.urls import path

from .views import (
                    VerDiarios,
                    EditarAlimentoDiario,
                    EliminarAlimentoDiario,
                    DetalleDiario,
                    BuscarDiarioApiView
                    )


app_name="diario_urls"

urlpatterns = [
    #path('mostrar/',,name="mostrar-mascotas"),
    path('ver-diarios/<pk>/',VerDiarios.as_view(),name="verdiario"),
    path('detalle-diario/<pk>/',DetalleDiario.as_view(),name="detallediario"),
    path('editar-alimento/<pk>/',EditarAlimentoDiario.as_view(),name="editalimento"),
    path('eliminar-alimento/<pk>/',EliminarAlimentoDiario.as_view(),name="eliminaralimento"),
    path('api/diarios/buscar/',BuscarDiarioApiView.as_view(),name="buscardiario"),

]

dam/dam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from applications.users.views import Index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/',include('applications.users.urls')),
    path('mascotas/',include('applications.mascotas.urls')),
    path('alimentos/',include('applications.alimentos.urls')),
    path('diario/',include('applications.diario.urls',namespace='diaro_urls')),
    path('',Index.as_view(),name="index")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dam/applications/diario/models.py
from django.db import models

from .managers import DiarioManager
from applications.mascotas.models import Mascota

# Create your models here.

COMIDAS_CHOICES=(
    ('1','1'),
    ('2','2'),
    ('3','3'),
)

class Diario(models.Model):
    fecha=models.DateField(auto_now_add=False)
    mascota=models.ForeignKey(Mascota,on_delete=models.CASCADE)
    comidas=models.CharField(max_length=1,choices=COMIDAS_CHOICES,blank=True,default=2)
    total_cal=models.PositiveIntegerField(blank=True,null=True,default=0)

    dif_cal=models.IntegerField(blank=True,null=True,default=0)
    completado=models.BooleanField(default=False)

    class Meta:
        unique_together=(("fecha","mascota"),)

    objects=DiarioManager()

    def __str__(self):
        return str(self.id)+' '+str(self.fecha) +' '+ self.mascota.nombre

    
    

    

dam/applications/diario/forms.py
from django import forms
from .models import Diario
from applications.alimentos.models import AlimentoConsumido


class BusquedaForm(forms.ModelForm):
    busqueda = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'Ingrese busqueda aqui',
                'class': 'input-group-field',
                
            }
        )
    )

class EditarAlimentoForm(forms.ModelForm):
    class Meta:
        #modelo al que se conecta
        model=AlimentoConsumido
        fields=(
            'cantidad', 
        )



    def __init__(self, *args, **kwargs):
        #saco el id de los kwargs
        alimentoid=kwargs.pop('pk','')
        #llamamos al constructor de la clase padre
        super(EditarAlimentoForm, self).__init__(*args, **kwargs)
        #y podemos acceder a las propiedades de los campos
        alimento=AlimentoConsumido.objects.get(pk=alimentoid)
        self.fields['cantidad'].required = True
        #self.fields['porcion'].required=True
        self.fields['cantidad'].initial=alimento.cantidad
        #self.fields['porcion'].initial=alimento.porcion
        


class CompletarDiarioForm(forms.ModelForm):
    class Meta:
        #modelo al que se conecta
        model=Diario
        fields=('id',)

dam/applications/diario/views.py
from datetime import datetime, timedelta

from rest_framework.generics import ListAPIView

from django.contrib import messages
from django.http.response import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.shortcuts import redirect

from .models import Diario
from .forms import (
                    EditarAlimentoForm,
                    CompletarDiarioForm
                    )

from .serializers import DiarioSerializer

from applications.alimentos.models import AlimentoConsumido
from applications.mascotas.models import Mascota,PesoMascotaDiario

# Create your views here.

class VerDiarios(LoginRequiredMixin,ListView):
    template_name="diario/ver_diarios.html"
    model = Diario
    context_object_name='lista_diario'
    paginate_by=4

    def dispatch(self, request, *args, **kwargs):
        #Asegurandome que solo los dueños de las mascotas puedan ver los diarios de sus mascotas 
        mascota=Mascota.objects.get(pk=self.kwargs.get('pk'))

        if mascota.dueño != self.request.user:
            messages.warning(self.request, 'Que hacemos metiendo mano en la url ?')
            return HttpResponseRedirect(reverse('mascotas_urls:listarmascotas'))
        
        return super(VerDiarios, self).dispatch(request, *args, **kwargs)

    #creacion del diario a partir del boton
    def get(self, request, *args, **kwargs):
       
        print('### ver diario get ###')
        print(self.kwargs['pk'])
        #fecha=self.request.POST.get('selectorFecha','')
        fecha=datetime.today()
        print('fecha ',fecha)   

        mascota=Mascota.objects.get(pk=self.kwargs['pk'])


        if fecha:
            print('hay fecha {}'.format(fecha))

            obj, created=Diario.objects.get_or_create(
            fecha=fecha,
            mascota=mascota,
            defaults={
                'mascota':mascota,
            }
            )

            #si se creo
            if created:
                print('diario creado')
                diario=Diario.objects.filter(mascota=mascota).order_by('-id')[0]
                self.pk=diario.id
                return HttpResponseRedirect(reverse('diario_urls:detallediario', kwargs={'pk': self.pk}))
            else:
                #si estaba creado
                print('ya existe un diario para esta fecha')
                return HttpResponseRedirect(reverse('diario_urls:detallediario', kwargs={'pk': obj.id}))
                
            
       
        else:
            print('no hay fecha')
            messages.info(self.request, 'Por favor introduzca una fecha valida')


        return redirect(request.build_absolute_uri())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mascota'] =Mascota.objects.get(pk=self.kwargs['pk']) 
        return context

    def get_queryset(self):
        palabra_clave=self.kwargs['pk']
        print(palabra_clave)
        return Diario.objects.buscar_diarios(palabra_clave).order_by('fecha')

class EditarAlimentoDiario(LoginRequiredMixin,FormView):
    template_name="diario/editar_alimento_diario.html"
    form_class=EditarAlimentoForm
    #success_url=reverse_lazy('diario_urls:detallediario')

    def dispatch(self, request, *args, **kwargs):
        #solo dueño puede editar alimento del diario de su mascota
        alimento=AlimentoConsumido.objects.get(pk=self.kwargs['pk'])
        diario = Diario.objects.get(pk=alimento.diario.id)
        mascota=Mascota.objects.get(pk=diario.mascota.id)

        if mascota.dueño != self.request.user:
            print(diario.id)
            messages.warning(self.request, 'Que hacemos metiendo mano en la url ?')
            return HttpResponseRedirect(reverse('mascotas_urls:listarmascotas'))
            #messages.success(self.request, 'Bienvenido!')

        return super(EditarAlimentoDiario, self).dispatch(request, *args, **kwargs)



    def form_valid(self, form):

        print("##POST##")
        
        cantidad=form.cleaned_data['cantidad']
        comida=AlimentoConsumido.objects.get(pk=self.kwargs['pk'])
        self.pk=comida.diario.id

        if cantidad != comida.cantidad:
            print('no son iguales, es {} y el form es {}'.format(comida.cantidad,form.cleaned_data['cantidad']))
            comida.cantidad=cantidad
            comida.save()
        else:
            print ('son iguales cantidad')
            

        return super(EditarAlimentoDiario,self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comida=AlimentoConsumido.objects.get(pk=self.kwargs['pk'])
        self.pk=comida.diario.id
        context['diario'] =Diario.objects.get(pk=self.pk) 
        return context
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['pk'] = self.kwargs['pk']
        return kwargs
    
    

    def get_success_url(self):
         return reverse('diario_urls:detallediario', kwargs={'pk': self.pk})


class EliminarAlimentoDiario(LoginRequiredMixin,TemplateView):
    template_name="diario/eliminar_alimento_diario.html"

    def dispatch(self, request, *args, **kwargs):
        #solo dueño puede eliminar alimento del diario de su mascota
        alimento=AlimentoConsumido.objects.get(pk=self.kwargs['pk'])
        diario = Diario.objects.get(pk=alimento.diario.id)
        mascota=Mascota.objects.get(pk=diario.mascota.id)

        if mascota.dueño != self.request.user:
            print(diario.id)
            messages.warning(self.request, 'Que hacemos metiendo mano en la url ?')
            return HttpResponseRedirect(reverse('mascotas_urls:listarmascotas'))

        return super(EliminarAlimentoDiario, self).dispatch(request, *args, **kwargs)



    def get(self, request, *args,**kwargs):
        print('##GET eliminaralimentodiario##')
        alimento=AlimentoConsumido.objects.get(pk=self.kwargs['pk'])
        #guardo el id del diario en una variable ya que voy a borrar el alimento de la db
        diarioid=alimento.diario.id

        if alimento:
            print(alimento.diario.id)
            alimento.delete()
            print('borrado')
            return HttpResponseRedirect(reverse('diaro_urls:detallediario',kwargs={'pk':diarioid}))

        return super(EliminarAlimentoDiario,self).get(request, *args, **kwargs)

    #en caso de q quiera volver a usar el delete view
    """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comida=AlimentoConsumido.objects.get(pk=self.kwargs['pk'])
        self.pk=comida.diario.id
        #context['diario'] =Diario.objects.get(pk=self.pk) 
        return context

    def get_success_url(self):
         return reverse('diario_urls:detallediario', kwargs={'pk': self.kwargs['diariopk']})"""

class DetalleDiario(LoginRequiredMixin,FormView,TemplateView):

    #formview
    form_class=CompletarDiarioForm
    template_name="diario/detalle_diario.html"
    #volver a detalle diario
    success_url=reverse_lazy('diario_urls:detallediario')

    def dispatch(self, request, *args, **kwargs):
        #Asegurandome que solo los dueños de las mascotas puedan ver los diarios de sus mascotas
        diario = Diario.objects.get(pk=self.kwargs.get('pk'))
        mascota=Mascota.objects.get(pk=diario.mascota.id)

        if mascota.dueño != self.request.user:
            messages.warning(self.request, 'Que hacemos metiendo mano en la url ?')
            return HttpResponseRedirect(reverse('mascotas_urls:listarmascotas'))
        #messages.success(self.request, 'Bienvenido!')
        
        return super(DetalleDiario, self).dispatch(request, *args, **kwargs)



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        diario=Diario.objects.get(pk=self.kwargs.get('pk'))
       
        context["diario"] = diario
        context['mascota']=Mascota.objects.get(pk=diario.mascota.id)
        context['comidas']=AlimentoConsumido.objects.buscar_alimentos_consumidos_fk(self.kwargs.get('pk'))
        return context

    def get(self, request, *args,**kwargs):
        print('##GET##')
        diario = Diario.objects.get(pk=self.kwargs.get('pk'))
        mascota=Mascota.objects.get(pk=diario.mascota.id)
        valor=self.request.GET.get('ir','')

        if valor=="atras":
            print('vamos atras')
            diarioayer=diario.fecha-timedelta(days=1)
            

            obj, created=Diario.objects.get_or_create(
            fecha=diarioayer,
            mascota=mascota,
            defaults={
                'mascota':mascota,
            }
            )

            if created:
                print('diario creado')
                diario=Diario.objects.get(mascota=mascota,fecha=diarioayer)
                return HttpResponseRedirect(reverse('diario_urls:detallediario', kwargs={'pk': diario.id}))
            else:
                #si estaba creado
                print('ya existe un diario para esta fecha')
                return HttpResponseRedirect(reverse('diario_urls:detallediario', kwargs={'pk': obj.id}))



        if valor=="adelante":
            print('vamos adelante')
            print(diario)
            diarioman=diario.fecha+timedelta(days=1)
            

            obj, created=Diario.objects.get_or_create(
            fecha=diarioman,
            mascota=mascota,
            defaults={
                'mascota':mascota,
            }
            )

            if created:
                print('diario creado mañana')
                diario=Diario.objects.get(mascota=mascota,fecha=diarioman)
                return HttpResponseRedirect(reverse('diario_urls:detallediario', kwargs={'pk': diario.id}))
            else:

dam/templates/diario/detalle_diario.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}Detalle diario{% endblock title %}

{% block content %}

<br>
{% language 'es' %}
<div class="container-fluid">
  <div class="row justify-content-center"> 

    <form id="formAtras" method="GET"  >
      <button title="Día anterior" 
      type="submit" class="btn btn-success">&laquo;</button>
      <input type="hidden" name="ir" value="atras">  
    </form>
      <div class="col-auto">
          <p class="h2" style="background-color: #D8DFEE ">
            Diario del dia {{ diario.fecha }} 
          </p>
      </div>
        <form id="formSiguiente" method="GET" >
          <button title="Día siguiente" 
          type="submit" class="btn btn-success">&raquo;</button>
          <input type="hidden" name="ir" value="adelante">    
        </form>

        <div class="container-fluid mt-2">
          <div class="row justify-content-center">
              <div title='Selecciona la fecha del diario que desea ir' class="col-auto mb-2">
                  <form id="formSelectorFecha" method="GET">
                      <p class="h6  mb-1">O seleccione una fecha</p>
                      <input type="date" name="selectorFecha" id="selectorFecha" >
                      <button type="submit" class="btn-sm btn-primary" >Ir</button>
                      <input type="hidden" name="ir" value="fechaSeleccionada">         
                  </form>
              </div>
          </div>
        </div>

  </div>
</div>
{% endlanguage %}


{% if messages %}
  {% for message in messages  %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
      <br>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} 
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
              
              {{ message }} <br>
              
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

<br>
<!--tabla prueba -->
<div class="col-sm-12 col-md-12 col-lg-8 col-xl-12 tm-block-col">
  <div class="tm-bg-primary-dark tm-block tm-block-products">
    <div class="tm-product-table-container">
      <table class="table table-hover tm-table-small tm-product-table">
        <thead>
          <tr>
              
            <th scope="col">&nbsp;</th>
            <th scope="col">Nombre</th>
            <th scope="col">Marca</th>
            <th scope="col">Calorias</th>
            <th scope="col"></th>
            <th scope="col"></th>
            
            
          </tr>
        </thead>
        <tbody>

          {% for i in comidas  %}
          <tr>
            <th scope="row"><!--<input type="checkbox" />--></th>
            <td class="tm-product-name">{{ i.alimento.nombre }}</td>
            <td>{{ i.alimento.marca }}</td>
            <td >{{ i.total_cal }}</td>
            
            <td>
              <a title="Editar" href="{% url 'diario_urls:editalimento' i.id %}">
               <img src="{% static 'iconos/modificar.svg' %}" width="18" height="24" alt="icono-editar">
              </a>
            </td>
            <td>
              <a title="Borrar" href="{% url 'diario_urls:eliminaralimento' i.id %}">                 
               <img src="{% static 'iconos/eliminar.svg' %}" width="18" height="24" alt="icono-eliminar">
              </a>
            </td>
          </tr>
          {% empty %}
              Todaviía no has cargado ningún alimento
          {% endfor %}

        </tbody>
      </table>
    </div>
    <!-- table container -->
    <a 
    href="{% url 'alimentos_urls:listar-alimentos' diario.id %}" class="btn btn-primary  text-uppercase mt-5">
    Agregar nuevo alimento
   </a>
  </div>
</div>
<!--fin tabla prueba-->

<div class="container-fluid">
    <div class="row justify-content-center"> 
      <div class="col-auto">

        <table class="table">
          <thead >
            <tr class="table table-borderless">
              <th scope="col">Calorias</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <tr class="table-secondary">
              <td>Total</td>
              <td id="tdtotalcal">{{ diario.total_cal }}</td>
            </tr>
            <tr class="table-secondary">
              <td>Meta</td>
              <td id="tdmeta">{{ mascota.meta }} </td>
            </tr>
            <tr class="table-secondary">
              <td>Restantes</td>
              <td id="tdresto"></td>
            </tr>
          </tbody>
        </table>

      </div>
  </div>
</div>

<br>


<div class="container-fluid">
  <div class="row justify-content-center"> 
    <div class="col-auto">
      <form method="post">
        {% csrf_token %}
        
        {% if diario.completado %}
          <button class="btn-sm btn-success mb-3" type="submit">Modificar diario</button>
          <input type="hidden" name="completar" id="completar" value="modificar">
        {% else %}
            <div class="row justify-content-center">
            
              <!-- paso fecha y peso del día para llevar un registro -->
              <label title="Actualización de peso opcional" for="peso">Peso mascota :&nbsp;</label>
              <input title="Actualización de peso opcional" type="number" name="peso" id="peso" min="0" max="1000" value="0" step=".01" size="5" >
              <!--<input type="hidden" name="fecha" id="fecha" value=" {{ diario.fecha }} ">-->
            </div>
          <button class="btn-sm btn-success mb-3 mt-3 ml-3" type="submit">Completar diario</button>
          <input type="hidden" name="completar" id="completar" value="completar">
          <input type="hidden" name="difcal" id="difcal" value="1">
          
        {% endif %}
      </form>
    </div>
  </div>
</div>

{% block scripts %}
<script type="text/javascript">
window.onload = function difCalorias() {
                  let totalcal = document.getElementById ( "tdtotalcal" ).innerText;
                  let meta = document.getElementById ( "tdmeta" ).innerText;
                  let resultado = Number(meta) - Number(totalcal);
                  document.getElementById("tdresto").innerText=resultado;
                  if (resultado<0){
                      console.log('te pasaste')
                      document.getElementById("tdresto").style.color = "red";
                  }
                  else if(resultado>=0){
                    console.log('vas bien')
                    document.getElementById("tdresto").style.color = "green";
                  };
                  
                }

</script>

{% endblock scripts %}



{% endblock content %}

dam/templates/diario/editar_alimento_diario.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Editar alimento{% endblock title %}

{% block content %}

<div class="container tm-mt-big tm-mb-big">
    <div class="row">
      <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
        <div class="tm-bg-primary-dark tm-block tm-block-h-auto">

          <div class="row">
            <div class="col-12">
              <h2 class="tm-block-title d-inline-block">Editar alimento</h2>
            </div>
          </div>
          
          <div class="row tm-edit-product-row">
            <div class="col-xl-6 col-lg-6 col-md-12">

              <form action="" method="post" class="tm-edit-product-form">

                {% csrf_token %}
                {{ form|crispy }}

                 <div class="col-12">
                     <button type="submit" class="btn btn-primary btn-block text-uppercase">Guardar</button>
                </div>

              </form>

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

{% endblock content %}

dam/templates/diario/eliminar_alimento_diario.html
{% extends 'base.html' %}
{% block title %}Eliminar alimento{% endblock title %}
{% block content %}

<div class="container tm-mt-big tm-mb-big">
    <div class="row">
      <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
        <div class="tm-bg-primary-dark tm-block tm-block-h-auto">

          <div class="row">
            <div class="col-12">
              <h2 class="tm-block-title d-inline-block">Editar alimento</h2>
            </div>
          </div>
          <div class="row tm-edit-product-row">
            <div class="col-xl-6 col-lg-6 col-md-12">
              <form action="" method="post" class="tm-edit-product-form">
                {% csrf_token %}
                <h1>¿Estas seguro de eliminar este alimento ?</h1>
                 <div class="col-12">
                     <button type="submit" class="btn btn-danger btn-block text-uppercase">Guardar</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

dam/templates/diario/ver_diarios.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Diarios{% endblock title %}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-auto mb-3">
        
{% if messages %}
  {% for message in messages  %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
      <br>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>
             <p class="text-center"> {{ message }}</p>
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      <br>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
          <strong>
             <p class="text-center"> {{ message }}</p>
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} 
      <br>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>
             <p class="text-center"> {{ message }}</p>
          </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endif %}

  {% endfor %}
{% endif %}
        </div>
    </div>
</div>

<div class="container-fluid mt-2">
    <div class="row justify-content-center">
        <div title='Selecciona la fecha del diario que desea ir' class="col-auto mb-4">
            <form method="POST">
                {% csrf_token %}
                <p class="h5 text-center mb-3">Seleccione una fecha</p>
                <input type="date" name="selectorFecha" id="selectorFecha" >
                <button type="submit" class="btn-sm btn-primary" >Ir</button>      
            </form>
        </div>
    </div>
</div>

{% endblock content %}